-- Generated by database/generate-word-lists-backfill.js — do not edit by hand.
-- Backfills word_lists / word_list_items from src/teachingTools/data/preset-wordlists.js

BEGIN TRANSACTION;
INSERT INTO word_lists (slug, name, description, theme, level, curriculum, owner_user_id)
VALUES (N'preset-hsk-1-essentials', N'HSK 1 Essentials', N'A compact, beginner-friendly starter pack for greetings, people, and classroom basics.', N'HSK 1', N'Beginner', N'HSK 1 starter', NULL);
DECLARE @listId INT = SCOPE_IDENTITY();
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'你好', N'nǐ hǎo', N'hello', NULL, NULL, 0);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'谢谢', N'xiè xie', N'thank you', NULL, NULL, 1);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'再见', N'zài jiàn', N'goodbye', NULL, NULL, 2);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'请', N'qǐng', N'please', NULL, NULL, 3);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'对不起', N'duì bu qǐ', N'sorry', NULL, NULL, 4);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'老师', N'lǎo shī', N'teacher', NULL, NULL, 5);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'学生', N'xué sheng', N'student', NULL, NULL, 6);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'朋友', N'péng you', N'friend', NULL, NULL, 7);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'人', N'rén', N'person', NULL, NULL, 8);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'我', N'wǒ', N'I; me', NULL, NULL, 9);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'你', N'nǐ', N'you', NULL, NULL, 10);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'他', N'tā', N'he; him', NULL, NULL, 11);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'她', N'tā', N'she; her', NULL, NULL, 12);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'是', N'shì', N'to be', NULL, NULL, 13);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'有', N'yǒu', N'to have', NULL, NULL, 14);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'喜欢', N'xǐ huan', N'to like', NULL, NULL, 15);
COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;
INSERT INTO word_lists (slug, name, description, theme, level, curriculum, owner_user_id)
VALUES (N'preset-food-and-fruit', N'Food & Fruit', N'Useful food vocabulary for cards, matching games, and speaking activities.', N'Food', N'Novice', N'Chen Laoshi curated', NULL);
DECLARE @listId INT = SCOPE_IDENTITY();
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'苹果', N'píng guǒ', N'apple', NULL, NULL, 0);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'香蕉', N'xiāng jiāo', N'banana', NULL, NULL, 1);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'草莓', N'cǎo méi', N'strawberry', NULL, NULL, 2);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'西瓜', N'xī guā', N'watermelon', NULL, NULL, 3);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'葡萄', N'pú tao', N'grapes', NULL, NULL, 4);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'橘子', N'jú zi', N'orange', NULL, NULL, 5);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'梨', N'lí', N'pear', NULL, NULL, 6);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'桃子', N'táo zi', N'peach', NULL, NULL, 7);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'米饭', N'mǐ fàn', N'rice', NULL, NULL, 8);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'面条', N'miàn tiáo', N'noodles', NULL, NULL, 9);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'饺子', N'jiǎo zi', N'dumplings', NULL, NULL, 10);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'水', N'shuǐ', N'water', NULL, NULL, 11);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'果汁', N'guǒ zhī', N'juice', NULL, NULL, 12);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'茶', N'chá', N'tea', NULL, NULL, 13);
COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;
INSERT INTO word_lists (slug, name, description, theme, level, curriculum, owner_user_id)
VALUES (N'preset-classroom-basics', N'Classroom Basics', N'High-frequency classroom objects and instructions for immediate use.', N'School', N'Novice', N'Chen Laoshi curated', NULL);
DECLARE @listId INT = SCOPE_IDENTITY();
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'书', N'shū', N'book', NULL, NULL, 0);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'本子', N'běn zi', N'notebook', NULL, NULL, 1);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'铅笔', N'qiān bǐ', N'pencil', NULL, NULL, 2);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'橡皮', N'xiàng pí', N'eraser', NULL, NULL, 3);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'尺子', N'chǐ zi', N'ruler', NULL, NULL, 4);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'桌子', N'zhuō zi', N'desk', NULL, NULL, 5);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'椅子', N'yǐ zi', N'chair', NULL, NULL, 6);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'黑板', N'hēi bǎn', N'blackboard', NULL, NULL, 7);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'请坐', N'qǐng zuò', N'please sit down', NULL, NULL, 8);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'请听', N'qǐng tīng', N'please listen', NULL, NULL, 9);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'请说', N'qǐng shuō', N'please speak', NULL, NULL, 10);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'请看', N'qǐng kàn', N'please look', NULL, NULL, 11);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'请读', N'qǐng dú', N'please read', NULL, NULL, 12);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'请写', N'qǐng xiě', N'please write', NULL, NULL, 13);
COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;
INSERT INTO word_lists (slug, name, description, theme, level, curriculum, owner_user_id)
VALUES (N'preset-weather-and-seasons', N'Weather & Seasons', N'A colorful set for seasonal warm-ups, forecasts, and speaking prompts.', N'Weather', N'Novice', N'Chen Laoshi curated', NULL);
DECLARE @listId INT = SCOPE_IDENTITY();
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'天气', N'tiān qì', N'weather', NULL, NULL, 0);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'太阳', N'tài yáng', N'sun', NULL, NULL, 1);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'云', N'yún', N'cloud', NULL, NULL, 2);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'雨', N'yǔ', N'rain', NULL, NULL, 3);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'雪', N'xuě', N'snow', NULL, NULL, 4);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'风', N'fēng', N'wind', NULL, NULL, 5);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'热', N'rè', N'hot', NULL, NULL, 6);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'冷', N'lěng', N'cold', NULL, NULL, 7);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'春天', N'chūn tiān', N'spring', NULL, NULL, 8);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'夏天', N'xià tiān', N'summer', NULL, NULL, 9);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'秋天', N'qiū tiān', N'autumn', NULL, NULL, 10);
INSERT INTO word_list_items (list_id, zh, py, en, img_blob_url, note, sort_order) VALUES (@listId, N'冬天', N'dōng tiān', N'winter', NULL, NULL, 11);
COMMIT TRANSACTION;
GO

